os:
  - linux
dist: trusty
sudo: required

services:
  - docker
  
before_script:
  - docker-compose up --build -d
  - pip install --user -r requirements.txt
  - sleep 10

script:
  - travis_wait 30 pytest -v test/