version: "2"
services:
  nginx:
    restart: always
    build: nginx/
    network_mode: "bridge"
    ports:
      - "80:80"
  db:
    restart: always
    build: .
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # NEO4J_dbms_read__only: "true"
      # NEO4J_dbms_shell_read__only: "true"
      #  Tuning
      # NEO4J_dbms_memory_pagecache_size: 8G
      # NEO4J_dbms_memory_heap_initial__size: 4G
      # NEO4J_dbms_memory_heap_max__size: 4G
    volumes_from:
      - dc
    network_mode: "bridge"
    ports:
      - "7687:7687"
      - "7474:7474"
  dc:
    build: dc/
    network_mode: "bridge"
    
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
