version: '2'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - db
      - es
  db:
    # restart: always
    build: . 
    environment:
      NEO4J_AUTH: none
    #  Tuning
      # NEO4J_dbms_memory_pagecache_size: 8G
      # NEO4J_dbms_memory_heap_initial__size: 4G
      # NEO4J_dbms_memory_heap_max__size: 4G
    volumes_from:
      - dc
    ports:
      - "7687:7687"
      - "7474:7474"
  dc:
    build: dc/
  es:
    # restart: always
    build: esdata/
    ports:
      - "9200:9200"
