version: "2"
services:
  db:
    # restart: always
    build: .
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_read__only: "false"
      #  Tuning
      # NEO4J_dbms_memory_pagecache_size: 8G
      # NEO4J_dbms_memory_heap_initial__size: 4G
      # NEO4J_dbms_memory_heap_max__size: 4G
    volumes_from:
      - dc
    network_mode: "bridge"
    ports:
      - "7687:7687"
      - "7474:7474"
  dc:
    build: dc/
    network_mode: "bridge"
  es:
    # restart: always
    build: esdata/
    network_mode: "bridge"
    ports:
      - "9200:9200"
