site_name: Combat-TB-NeoDB
nav:
  - Combat-TB-NeoDB documentation: index.md
  - Installation: installation.md
  - Querying using Cypher: cypher-example.md
  - Querying using Python: python-example.md
  - Graph Algorithms: graph-algorithms.md

  # - About: about.md
theme: readthedocs
