site_name: COMBAT-TB NeoDB
nav:
  - Welcome to NeoDB's documentation!: index.md
  - Installation: installation.md
  - Interacting with NeoDB using Cypher : cypher-example.md
  - Interacting with NeoDB using Python : python-example.md
  - Graph Algorithms in NeoDB: graph-algorithms.md

  # - About: about.md
theme: readthedocs
