version: "3.2"
services:
  db:
    image: quay.io/combat-tb/combattb-db:dev
    environment:
      NEO4J_AUTH: none
    volumes:
      - data-volume:/data
    ports:
      - "7687:7687"
      - "7474:7474"
  dc:
    image: quay.io/combat-tb/combattb-dc:dev
    volumes:
      - data-volume:/data
  es:
    image: quay.io/combat-tb/combattb-es:dev
    ports:
      - "9200:9200"
volumes:
  data-volume:
    external: false
